
services:
  postgres:
    image: postgres:17.6-alpine
    container_name: kayra-postgres
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: kayraexp
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: